title: "Mohammad Talebi Kalaleh"
description: "My CV site for structural engineering research, projects, and teaching."
theme:  # or leave empty if you want to handle all styling yourself
baseurl: ""
url: "https://talebika.github.io"  # Replace with your GitHub Pages URL
markdown: kramdown

# (Optional) Social links or other config variables you might need:
github_username: mtalebi
linkedin_username: www.linkedin.com/in/mtkalaleh

# Exclude files you do not want processed (if any):
exclude:
  - README.md
